### PR TITLE
Changed style

### PR DESCRIPTION
**Pull request by Bicheka**
changed a few styles to make it a little bit more modern;

changed the profile icon on hover;
changed notes box shadow a little bit
(check commit notes)

### CODE REVIEW

**Review by narainkarthikv — CHANGES_REQUESTED** [review]
Hey Bicheka, I want the font family to be "Outfit" and implemented throughout all texts, in application only nav-brand has been changed. Can you help me with it?

```html
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@700&display=swap');

**Review by narainkarthikv — APPROVED** [review]
Thank you @Bicheka for your valuable contribution! Looking forward to more great work from you in the future.

**Review by narainkarthikv — CHANGES_REQUESTED** [review]
The code has been updated recently @Bicheka , Pull the remote repository and work with the recent updated codebase with the font style requested "Outfit".

```html
@import url('https://fonts.googleapis.com/css2?family=Outfit:wght@700&display=swap');
```

Happy Contributing

**Comment by Bicheka** [comment]
let me see how can I fix all the conflicts that there are

**Pull request closed without merging**
