### PR TITLE
ui and color scheme changed and responsive design also added

### PR DESCRIPTION
**Pull request by Divyverma**
Hello there,
i have added the new color scheme for your web application and also done some changes in ui as you have metioned. 
also added responsive design for mobile.
Hope you like the design.

### CODE REVIEW

**Review by narainkarthikv — CHANGES_REQUESTED** [review]
@Divyverma, please follow these steps while working on the feature branch:

- Review the `README.md` for detailed guidance on the project setup and workflow.
- To avoid confusion, carefully go through Issue #19 to understand the specific tasks required.
- Ensure that the `BoardList` component is not removed during your work.
- If possible, test the responsiveness of your changes before submitting.

Once completed, please submit a Merge Request (MR) for review.

Thank you!

**Comment by Divyverma** [comment]
hey i have added dark and light theme functionality, provide me the color code show i can add them.

**Comment by narainkarthikv** [comment]
> Hey, I have added dark and light theme functionality. Please provide the color codes so I can add them.

**Color Codes:**

- **All Notes**: `lightgoldenyellow` (Can be dynamically set to any color by the user using JavaScript)
- **Held Notes**: `lightseablue`  (Can be dynamically set to any color by the user using JavaScript)
- **Checked Notes**: `lightgreen`  (Can be dynamically set to any color by the user using JavaScript)

**Comment by Divyverma** [comment]
and the other colors are okay??

**Comment by narainkarthikv** [comment]
> Are the other colors okay?

Yes, they are fine. Just make sure not to comment out components or other imported code, as this can cause issues during the build process on Netlify. Please check your terminal for any possible warnings or errors before submitting a PR.

**Comment by narainkarthikv** [comment]
Hi @Divyverma,

I've recently updated all the file names to improve the directory structure. Could you please close this PR and create a new one? There are several issues that need attention. Please work on a feature branch and submit a new PR.

**Note:** Make sure to check for any warnings in the terminal beforehand to avoid merge conflicts and issues with the Netlify build.

Thank you!

**Pull request closed without merging**
